ssl_name: meclip
data:
  batch_size: 32
  color_jitter_strength: 0.0
  crop_scale:
  - 0.3
  - 1.0
  crop_size: 2500
  num_workers: 10
  pin_mem: true
  use_color_distortion: false
  use_gaussian_blur: false
  use_gaussian_noise: false
  use_horizontal_flip: false
  clean: true
  trainss:
    - x_path: /home/achil/src/ml/icmhi/ecgs/xfake-32.csv
      normalization: [[-0.8882988483035262,],[33.28235233265648,]]
  in_chans: 12
  x_label: ecg
  vocab_path: /home/achil/src/ml/icmhi/ecgs/md-validated-5-diagnosis.json
  text_model_path: /home/achil/src/ml/icmhi/ecgs/md-validated-5-diagnosis.model
  text_vocab_path: /home/achil/src/ml/icmhi/ecgs/md-validated-5-diagnosis.vocab
logging:
  folder: output/logs/ecg_vib25_ep.300/
  write_tag: cdc
  project: ecg-ssl
  name: ssl-1
meta:
  copy_data: false
  load_checkpoint: true
  model_name: ecgresnet_1d34
  projection_name: cls_proj_dims=512,512,192_bn
  text_encoder_name: textt_tiny
  read_checkpoint: 
  use_bfloat16: false
loss:
  temperature: 0.1
  off_diag: true
  mutually_exclusive: true
optimization:
  strategy: linear-warmup-cosine
  ema:
  - 0.996
  - 1.0
  epochs: 15
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  ipe_scale: 1.0
  lr: 0.001
  start_lr: 0.0002
  warmup: 40
  weight_decay: 0.04
  grad_clip: 10.
