ssl_name: simclr
data:
  batch_size: 128
  color_jitter_strength: 0.0
  crop_scale:
  - 0.3
  - 1.0
  crop_size: 1000
  num_workers: 10
  pin_mem: true
  use_color_distortion: false
  use_gaussian_blur: 0.5
  use_horizontal_flip: false
  clean: true
  train:
    - x_path: /home/achil/src/ml/icmhi/ecgs/md-validated-train-500.csv
    - x_path: /home/achil/src/ml/icmhi/ecgs/xfake-32.csv
      normalization: [[-0.8882988483035262,],[33.28235233265648,]]
    - x_path: /home/achil/src/ml/icmhi/ecgs/xfake-32.npy
      normalization: /home/achil/src/ml/icmhi/ecgs/scaler_train_12c.pkl
  in_chans: 12
  x_label: ecg

logging:
  folder: output/logs/ecg_vib25_ep.300/
  write_tag: simclr
  project: ecg-ssl
  name: ssl-1
meta:
  copy_data: false
  load_checkpoint: false
  model_name: ecgresnet_1d34
  projection_name: cls_proj_dims=512,512,128_bn
  pred_depth: 12
  pred_emb_dim: 384
  predictor_name: ecgt_predictor
  read_checkpoint: null
  use_bfloat16: false
optimization:
  strategy: linear-warmup-cosine
  ema:
  - 0.996
  - 1.0
  epochs: 1
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  ipe_scale: 1.0
  lr: 0.001
  start_lr: 0.0002
  warmup: 40
  weight_decay: 0.04
  temperature: 0.1
  grad_clip: 10.
